# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50, unique=True)),
                ('c_create_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=50, unique=True)),
                ('e_label', models.CharField(max_length=30)),
                ('e_content', models.TextField(max_length=30)),
                ('e_create_time', models.DateTimeField(auto_now_add=True)),
                ('e_operate_time', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'essay',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_name', models.CharField(max_length=50, unique=True)),
                ('n_create_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'notice',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=20, unique=True)),
                ('p_alias', models.CharField(max_length=20, unique=True)),
                ('p_keyword', models.CharField(max_length=20, unique=True)),
                ('p_description', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'part',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=20, unique=True)),
                ('u_pwd', models.CharField(max_length=225, unique=True)),
                ('u_create_time', models.DateTimeField(auto_now_add=True)),
                ('u_login_time', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('out_time', models.DateTimeField(default=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u0', to='blogweb.Users')),
            ],
            options={
                'db_table': 'user_ticket',
            },
        ),
        migrations.AddField(
            model_name='notice',
            name='n_auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u2', to='blogweb.Users'),
        ),
        migrations.AddField(
            model_name='essay',
            name='e_auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u1', to='blogweb.Users'),
        ),
        migrations.AddField(
            model_name='essay',
            name='e_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ess', to='blogweb.Part'),
        ),
        migrations.AddField(
            model_name='comment',
            name='c_auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u3', to='blogweb.Users'),
        ),
        migrations.AddField(
            model_name='comment',
            name='c_com',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c1', to='blogweb.Essay'),
        ),
    ]
